removing integration test on pre-release from dev

diff --git a/.github/workflows/manual-create-pre-release-from-dev.yml b/.github/workflows/manual-create-pre-release-from-dev.yml
--- a/.github/workflows/manual-create-pre-release-from-dev.yml
+++ b/.github/workflows/manual-create-pre-release-from-dev.yml
@@ -92,34 +92,34 @@ jobs:
           git commit --allow-empty -m "Chart.yaml updated with new version v${{ steps.semantic-release-dryrun.outputs.new_release_version }}"
           git push
 
-      - name: Test and Integration tests
-        run: |
-          mvn test -Dquarkus.package.type=native -Dquarkus.application.name=atm-layer-wf-process -Dquarkus.profile=prod
+      # - name: Test and Integration tests
+      #   run: |
+      #     mvn test -Dquarkus.package.type=native -Dquarkus.application.name=atm-layer-wf-process -Dquarkus.profile=prod
 
-      - name: Create Status check based on postman results
-        id: process-postman
-        uses: im-open/process-postman-test-results@v2.1.5
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          results-file: src/test/resources/integration-test/output/result.json
-          report-name: 'Postman create pre-release: ${{ github.run_number }}'
-          create-status-check: true
-          create-pr-comment: true
-          update-comment-if-one-exists: true
-          ignore-test-failures: true
-          timezone: 'europe/rome'
+      # - name: Create Status check based on postman results
+      #   id: process-postman
+      #   uses: im-open/process-postman-test-results@v2.1.5
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     results-file: src/test/resources/integration-test/output/result.json
+      #     report-name: 'Postman create pre-release: ${{ github.run_number }}'
+      #     create-status-check: true
+      #     create-pr-comment: true
+      #     update-comment-if-one-exists: true
+      #     ignore-test-failures: true
+      #     timezone: 'europe/rome'
 
-      - name: Fail if there were errors in the postman tests
-        if: steps.process-postman.outputs.test-outcome == 'Failed'
-        run: |
-          echo "There were postman failures."
-          exit 1
+      # - name: Fail if there were errors in the postman tests
+      #   if: steps.process-postman.outputs.test-outcome == 'Failed'
+      #   run: |
+      #     echo "There were postman failures."
+      #     exit 1
 
-      - name: Upload result.html
-        uses: actions/upload-artifact@v3
-        with:
-          name: html-report
-          path: src/test/resources/integration-test/output/result.html
+      # - name: Upload result.html
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: html-report
+      #     path: src/test/resources/integration-test/output/result.html
 
       # - name: JaCoCo Code Coverage Report
       #   id: jacoco_reporter
